### PR TITLE
Parallax Container

### LINKED ISSUE #25: Parallax Container
- Should this be a separate block?
- Should we create another column variant? Parallax?

image

https://www.audi.co.uk/uk/web/en/used-cars/used-electric-and-hybrid.html

### PR DESCRIPTION
**Pull request by LucaNerlich**
Added (parallax) block variation for column blocks with 2 columns and one image. 

Fix #25 

Reference Site:
- https://www.audi.co.uk/uk/web/en/used-cars/used-electric-and-hybrid.html

Draft URL:
- https://25-parallax-container--audi--aemsites.hlx.live/uk/web/en/drafts/columns

Test URLs:
- Before: https://main--audi--aemsites.hlx.live/uk/web/en/used-cars/used-electric-and-hybrid
- After: https://25-parallax-container--audi--aemsites.hlx.live/uk/web/en/used-cars/used-electric-and-hybrid

### CODE REVIEW

**Review by kunwarsaluja — CHANGES_REQUESTED** [review]
@LucaNerlich  tiny layout issue with  button widths in lower screen sizes, Can you check ? OR does it apply for all buttons globally ?

Screenshot 2024-03-12 at 9 44 00 AM

**Comment by LucaNerlich** [comment]
> @LucaNerlich tiny layout issue with button widths in lower screen sizes, Can you check ? OR does it apply for all buttons globally ?
> 
> Screenshot 2024-03-12 at 9 44 00 AM

hm. The buttons should be "secondary" button anyways. I guess the css has gotten overwritten / the content was changed. Ill take a look.

**Comment by LucaNerlich** [comment]
@kunwarsaluja I think this was due to cached old content.
This is how it looks for me right now:

image
https://25-parallax-container--audi--aemsites.hlx.live/uk/web/en/used-cars/used-electric-and-hybrid

I am not sure what to do on super narrow screens:
image

**Comment by kunwarsaluja** [comment]
> @kunwarsaluja I think this was due to cached old content. This is how it looks for me right now:
> 
> image https://25-parallax-container--audi--aemsites.hlx.live/uk/web/en/used-cars/used-electric-and-hybrid
> 
> I am not sure what to do on super narrow screens: image

@LucaNerlich I think we can piggyback on what they have today on the live site with appropriate padding/margin/warp, See https://www.audi.co.uk/uk/web/en/used-cars/used-electric-and-hybrid.html

Screenshot 2024-03-12 at 11 49 47 AM

**Comment by LucaNerlich** [comment]
@kunwarsaluja should be fixed now:

image

ive moved the icon to :forward: content, instead of `::after` and added styling.

**Review by kunwarsaluja — APPROVED** [review]

**Pull request merged**
