### PR TITLE
Hero

### LINKED ISSUE #4: Hero
**Desktop**
Screenshot 2024-03-01 at 2 57 56 PM

**Mobile**
Screenshot 2024-03-01 at 2 58 19 PM

**Variation 1** (https://www.audi.co.uk/uk/web/en/used-cars/used-electric-and-hybrid.html)
Screenshot 2024-03-04 at 6 07 36 PM

Screenshot 2024-03-04 at 6 12 21 PM

**Variation 2** (https://www.audi.co.uk/uk/web/en/used-cars/used-electric-and-hybrid.html)
Screenshot 2024-03-04 at 6 09 45 PM

Screenshot 2024-03-04 at 6 09 59 PM

### PR DESCRIPTION
**Pull request by markusbulla**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #4 

Draft URL:
- https://4-hero--audi--aemsites.hlx.live/uk/web/en/drafts/hero

Test URLs:
- Before: https://main--audi--aemsites.hlx.live/uk/web/en/used-cars
- After: https://4-hero--audi--aemsites.hlx.live/uk/web/en/used-cars

### CODE REVIEW

**Comment by markusbulla** [comment]
First draft PR with default hero block for 3 different view ports (<768; 768-1023; >=1024). 
Will continue work on the two variations of the hero block.

**Review by LucaNerlich — CHANGES_REQUESTED** [review]
Hi Markus,

few things ive noticed:

- in general, the hero image is way too large
- there is now margin or padding between the hero block bottom and the subnav
- the buttons are not clickable on desktop width
- please update the hero content in sharepoint on all pages

image

**Comment by amol-anand** [comment]
@markusbulla please don't add any package.json or package-lock changes to your PRs. you can safely ignore them.

**Comment by LucaNerlich** [comment]
image

hero (variation1) - text content is not centered on desktop

**Comment by markusbulla** [comment]
> @markusbulla please don't add any package.json or package-lock changes to your PRs. you can safely ignore them.

Changes to package.json and package-lock have been removed. 

>     * in general, the hero image is way too large
>     * the buttons are not clickable on desktop width

These two points have been resolved.

**Review by amol-anand — APPROVED** [review]

**Pull request merged**
