### PR TITLE
6 - Global Styles

### LINKED ISSUE #6: Global Styles
Get the global styles / fonts etc from the current site and set it in our styles.css 

See list below 

- [ ]  Headings
- [ ]  Margins
- [x]  Custom Fonts
- [ ]  Font size
- [ ]  Colors
- [ ]  Buttons (primary, secondary)
- [ ]  Media queries & Breakpoints
- [ ]  Section widths

### PR DESCRIPTION
**Pull request by LucaNerlich**
Updates root styles.css with audi global styles

Test URLs:
- Before: https://main--audi--aemsites.hlx.live/uk/web/en/used-cars
- After: https://6-global-styles--audi--aemsites.hlx.live/uk/web/en/used-cars

### CODE REVIEW

**Comment by kunwarsaluja** [comment]
@LucaNerlich  See if the updates to this PR makes sense. Obviously i might have missed few things but we can handle them as they come. Feel free to reject or add to these changes.

**Comment by LucaNerlich** [comment]
We need the ::selection part i believe. Used Cars has a red-background effect in text-selection.

**Comment by LucaNerlich** [comment]
image

when we add :forward: after a secondary button, the icon is not vertically centered

**Review by kunwarsaluja — APPROVED** [review]

**Comment by LucaNerlich** [comment]
fixed vertical icon alignment via https://github.com/aemsites/audi/pull/8/commits/9ddbf532c0b532c0123aa7a6130a0c2c362b83f7

**Pull request merged**
